name: build

on: 
  push:
    paths: 
      - build/**
      - .github/workflows/build.yml

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          ANDROID_NDK_HOME=$(pwd)/android-ndk-r15c
      - name: Build
        run: |
          cd build
          ./make_android_lua53.sh
      - name: Upload53
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua53/**/*
          name: plugin_lua53   
  
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build
          ./make_ios_lua53.sh
          ./make_ios_luajit.sh
      - name: Upload53
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua53/**/*
          name: plugin_lua53 
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit
  osx:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build
          ./make_osx_lua53.sh
          ./make_osx_luajit.sh
      - name: Upload53
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua53/**/*
          name: plugin_lua53   
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit  
